In [4]:
import rif
from rif.actor import Atom

import numpy as np
print(Atom.dtype.names)

('pos', 'atype', 'anum', 'rtype')


In [5]:
a = np.zeros(5, dtype=Atom)
a['pos']['raw'] = np.arange(15).reshape(5,3)
a['rtype'] = np.arange(5)
print(a)
b = a.view('4f4')
m = b[:,3].copy()
b[:,3] = 1.0
print(b)
print(a)
b[:,3] = m
print(a)


[(([  0.,   1.,   2.],), 0, 0, 0) (([  3.,   4.,   5.],), 0, 0, 1)
 (([  6.,   7.,   8.],), 0, 0, 2) (([  9.,  10.,  11.],), 0, 0, 3)
 (([ 12.,  13.,  14.],), 0, 0, 4)]
[[  0.   1.   2.   1.]
 [  3.   4.   5.   1.]
 [  6.   7.   8.   1.]
 [  9.  10.  11.   1.]
 [ 12.  13.  14.   1.]]
[(([  0.,   1.,   2.],), 0, 0, 16256) (([  3.,   4.,   5.],), 0, 0, 16256)
 (([  6.,   7.,   8.],), 0, 0, 16256) (([  9.,  10.,  11.],), 0, 0, 16256)
 (([ 12.,  13.,  14.],), 0, 0, 16256)]
[(([  0.,   1.,   2.],), 0, 0, 0) (([  3.,   4.,   5.],), 0, 0, 1)
 (([  6.,   7.,   8.],), 0, 0, 2) (([  9.,  10.,  11.],), 0, 0, 3)
 (([ 12.,  13.,  14.],), 0, 0, 4)]


In [8]:
a = np.arange(7)
np.dot(a  a

91